### ISSUE TITLE
Can't get migrations to work

### ISSUE THREAD

**Issue by stochastic-thread** [gogogarrett/phoenix_crud#3]
I ran `mix ecto.migrate PhoenixCrud.repo` but got this error:

```
[error] Loading of /Users/arthur/Code/elixir/web_apps/phoenix_crud/_build/dev/lib/phoenix_crud/ebin/Elixir.PhoenixCrud.repo.beam failed: :badfile

[error] beam/beam_load.c(1250): Error loading module 'Elixir.PhoenixCrud.repo':
  module name in object code is Elixir.PhoenixCrud.Repo


** (Mix.Error) could not load :"Elixir.PhoenixCrud.repo", error: :badfile
    (ecto) lib/mix/ecto.ex:35: Mix.Ecto.ensure_repo/1
    (ecto) lib/mix/tasks/ecto.migrate.ex:44: Mix.Tasks.Ecto.Migrate.run/2
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
    (elixir) lib/code.ex:316: Code.require_file/2
```

I then thought maybe I should run`mix ecto.migrate Elixir.PhoenixCrud.repo` but got this error:

```
[error] Loading of /Users/arthur/Code/elixir/web_apps/phoenix_crud/_build/dev/lib/phoenix_crud/ebin/Elixir.PhoenixCrud.repo.beam failed: :badfile

[error] beam/beam_load.c(1250): Error loading module 'Elixir.PhoenixCrud.repo':
  module name in object code is Elixir.PhoenixCrud.Repo


** (Mix.Error) could not load :"Elixir.PhoenixCrud.repo", error: :badfile
    (ecto) lib/mix/ecto.ex:35: Mix.Ecto.ensure_repo/1
    (ecto) lib/mix/tasks/ecto.migrate.ex:44: Mix.Tasks.Ecto.Migrate.run/2
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
    (elixir) lib/code.ex:316: Code.require_file/2
```

Any pointers would be appreciated, thanks

**Comment by stochastic-thread** [comment]
Had to edit config/config.exs with my username/password, my bad
